version: '3.7'

services:
  base: &base
    build:
      context: .
    volumes:
      - ./src:/usr/src/app/src
    env_file: .env
  dev:
    <<: *base
    ports:
      - 8080:8080
    command: "npm run start:dev"

  test:
    <<: *base
    command: "npm run test"
